### PR TITLE
Add configurable node version

### LINKED ISSUE #30: Node version is not configurable
Need to be able to specify node version

### PR DESCRIPTION
**Pull request by likeuntomurphy**
Fixes #30

### CODE REVIEW

**Comment by kellypacker** [comment]
@likeuntomurphy how would I test this?

**Comment by likeuntomurphy** [comment]
`cd ansible/roles && git checkout -b feature/configurable-node-version origin/feature/configurable-node-version`

Add an earlier `node_version` to  `ansible/group_vars/all` (à la https://github.com/fostermadeco/development-standard/pull/16/files#diff-2d879ae862e88c1fe4c4e19affaeffddR23) and provision or re-provision a VM.

From the VM, check that node is the correct version.

**Comment by kellypacker** [comment]
I'm on the right branch in the submodule because I see the changes to the file, but I'm getting this when trying to `vagrant provision`:
screenshot 2018-04-03 15 13 06

**Comment by likeuntomurphy** [comment]
Arggh, that was a yaml indentation issue. I fixed it.

**Comment by kellypacker** [comment]
This works for me. I tried version 6 and then destroyed and switched it to version 8.

**Review by kellypacker — COMMENTED** [review]
works

**Pull request merged**
